import { readFile } from "node:fs/promises";

import {
  assertFails,
  assertSucceeds,
  initializeTestEnvironment,
  type RulesTestEnvironment,
} from "@firebase/rules-unit-testing";
import firebase from "firebase/compat/app";
import "firebase/compat/firestore";
import { afterAll, beforeAll, beforeEach, describe, it } from "vitest";

const projectId = "demo-gomoku2d-rules-test";

let testEnv: RulesTestEnvironment;

function timestamp(iso: string): firebase.firestore.Timestamp {
  return firebase.firestore.Timestamp.fromDate(new Date(iso));
}

function serverTimestamp(): firebase.firestore.FieldValue {
  return firebase.firestore.FieldValue.serverTimestamp();
}

function ownerDb(uid = "uid-1"): firebase.firestore.Firestore {
  return testEnv.authenticatedContext(uid).firestore();
}

function profileDocument(uid: string, overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    auth_providers: ["google.com"],
    avatar_url: "https://example.com/avatar.png",
    created_at: timestamp("2020-01-01T00:00:00.000Z"),
    display_name: "Bryan",
    email: "bryan@example.com",
    history_reset_at: null,
    last_login_at: timestamp("2020-01-01T00:00:00.000Z"),
    preferred_variant: "freestyle",
    recent_matches: {
      matches: [],
      schema_version: 1,
      updated_at: null,
    },
    schema_version: 2,
    uid,
    updated_at: timestamp("2020-01-01T00:00:00.000Z"),
    username: null,
    ...overrides,
  };
}

function profileCreateDocument(uid: string, overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    ...profileDocument(uid),
    created_at: serverTimestamp(),
    last_login_at: serverTimestamp(),
    updated_at: serverTimestamp(),
    ...overrides,
  };
}

function profileUpdateDocument(uid: string, overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    ...profileDocument(uid),
    last_login_at: serverTimestamp(),
    updated_at: serverTimestamp(),
    ...overrides,
  };
}

async function seedProfile(uid: string, overrides: Record<string, unknown> = {}): Promise<void> {
  await testEnv.withSecurityRulesDisabled(async (context) => {
    await context.firestore().doc(`profiles/${uid}`).set(profileDocument(uid, overrides));
  });
}

async function seedMatch(uid: string, matchId: string, document: Record<string, unknown>): Promise<void> {
  await testEnv.withSecurityRulesDisabled(async (context) => {
    await context.firestore().doc(`profiles/${uid}/matches/${matchId}`).set(document);
  });
}

function recentMatchesUpdate(matches: unknown[] = []): Record<string, unknown> {
  return {
    matches,
    schema_version: 1,
    updated_at: serverTimestamp(),
  };
}

beforeAll(async () => {
  const rules = await readFile(new URL("../../../firestore.rules", import.meta.url), "utf8");
  testEnv = await initializeTestEnvironment({
    projectId,
    firestore: { rules },
  });
});

beforeEach(async () => {
  await testEnv.clearFirestore();
});

afterAll(async () => {
  await testEnv.cleanup();
});

describe("Firestore profile rules", () => {
  it("allows the owner to create and read their profile only", async () => {
    await assertSucceeds(ownerDb().doc("profiles/uid-1").set(profileCreateDocument("uid-1")));
    await assertSucceeds(ownerDb().doc("profiles/uid-1").get());
    await assertFails(ownerDb("uid-2").doc("profiles/uid-1").get());
    await assertFails(testEnv.unauthenticatedContext().firestore().doc("profiles/uid-1").get());
  });

  it("allows reset barriers only when they are generated by the write request", async () => {
    await seedProfile("uid-1");

    await assertSucceeds(
      ownerDb().doc("profiles/uid-1").set(
        profileUpdateDocument("uid-1", {
          history_reset_at: serverTimestamp(),
          recent_matches: recentMatchesUpdate(),
        }),
      ),
    );

    await assertFails(
      ownerDb().doc("profiles/uid-1").set(
        profileUpdateDocument("uid-1", {
          history_reset_at: timestamp("2020-01-01T00:00:00.000Z"),
        }),
      ),
    );
  });

  it("allows reset barriers to bypass the normal profile update cooldown", async () => {
    await seedProfile("uid-1", {
      history_reset_at: null,
      updated_at: timestamp("2999-01-01T00:00:00.000Z"),
    });

    await assertSucceeds(
      ownerDb().doc("profiles/uid-1").set(
        profileUpdateDocument("uid-1", {
          history_reset_at: serverTimestamp(),
          recent_matches: recentMatchesUpdate(),
        }),
      ),
    );
  });

  it("rejects rapid profile updates inside the server-side cooldown", async () => {
    await seedProfile("uid-1", {
      updated_at: timestamp("2999-01-01T00:00:00.000Z"),
    });

    await assertFails(
      ownerDb().doc("profiles/uid-1").set(
        profileUpdateDocument("uid-1", {
          display_name: "Rapid Edit",
        }),
      ),
    );
  });

  it("allows profile updates after the server-side cooldown", async () => {
    await seedProfile("uid-1", {
      updated_at: timestamp("2020-01-01T00:00:00.000Z"),
    });

    await assertSucceeds(
      ownerDb().doc("profiles/uid-1").set(
        profileUpdateDocument("uid-1", {
          display_name: "Settled Edit",
        }),
      ),
    );
  });

  it("allows one initial profile sync immediately after profile creation", async () => {
    await seedProfile("uid-1", {
      created_at: timestamp("2999-01-01T00:00:00.000Z"),
      updated_at: timestamp("2999-01-01T00:00:00.000Z"),
    });

    await assertSucceeds(
      ownerDb().doc("profiles/uid-1").set(
        profileUpdateDocument("uid-1", {
          created_at: timestamp("2999-01-01T00:00:00.000Z"),
          display_name: "Promoted Local Name",
          preferred_variant: "renju",
          recent_matches: recentMatchesUpdate([
            {
              id: "match-1",
            },
          ]),
        }),
      ),
    );
  });

  it("allows old alpha profiles to be refreshed into profile schema v2", async () => {
    await testEnv.withSecurityRulesDisabled(async (context) => {
      const legacyProfile = profileDocument("uid-1", {
        schema_version: 1,
      });
      delete legacyProfile.recent_matches;
      await context.firestore().doc("profiles/uid-1").set(legacyProfile);
    });

    await assertSucceeds(
      ownerDb().doc("profiles/uid-1").set(
        profileUpdateDocument("uid-1", {
          recent_matches: recentMatchesUpdate(),
        }),
      ),
    );
  });

  it("does not allow the initial profile sync bypass after a later profile update", async () => {
    await seedProfile("uid-1", {
      created_at: timestamp("2020-01-01T00:00:00.000Z"),
      updated_at: timestamp("2999-01-01T00:00:00.000Z"),
    });

    await assertFails(
      ownerDb().doc("profiles/uid-1").set(
        profileUpdateDocument("uid-1", {
          display_name: "Rapid Followup",
        }),
      ),
    );
  });

  it("does not allow the owner to remove an existing reset barrier", async () => {
    await seedProfile("uid-1", {
      history_reset_at: timestamp("2020-01-01T00:00:00.000Z"),
    });

    const update = profileUpdateDocument("uid-1");
    delete update.history_reset_at;

    await assertFails(ownerDb().doc("profiles/uid-1").set(update));
  });

  it("does not allow a reset write to move an existing barrier backward", async () => {
    await seedProfile("uid-1", {
      history_reset_at: timestamp("2999-01-01T00:00:00.000Z"),
    });

    await assertFails(
      ownerDb().doc("profiles/uid-1").set(
        profileUpdateDocument("uid-1", {
          history_reset_at: serverTimestamp(),
          recent_matches: recentMatchesUpdate(),
        }),
      ),
    );
  });

  it("rejects arbitrary reset barriers during profile creation", async () => {
    await assertFails(
      ownerDb("uid-2").doc("profiles/uid-2").set(
        profileCreateDocument("uid-2", {
          history_reset_at: timestamp("2020-01-01T00:00:00.000Z"),
        }),
      ),
    );
  });

  it("allows embedded recent history in a settled profile snapshot update", async () => {
    await seedProfile("uid-1", {
      updated_at: timestamp("2020-01-01T00:00:00.000Z"),
    });

    await assertSucceeds(
      ownerDb().doc("profiles/uid-1").set(
        profileUpdateDocument("uid-1", {
          recent_matches: recentMatchesUpdate([
            {
              id: "match-1",
            },
          ]),
        }),
      ),
    );
  });

  it("rejects embedded recent history snapshots over the cap", async () => {
    await seedProfile("uid-1", {
      updated_at: timestamp("2020-01-01T00:00:00.000Z"),
    });

    await assertFails(
      ownerDb().doc("profiles/uid-1").set(
        profileUpdateDocument("uid-1", {
          recent_matches: recentMatchesUpdate(Array.from({ length: 25 }, (_, index) => ({ id: `match-${index}` }))),
        }),
      ),
    );
  });

  it("rejects embedded recent history changes without a server timestamp", async () => {
    await seedProfile("uid-1");

    await assertFails(
      ownerDb().doc("profiles/uid-1").set(
        profileUpdateDocument("uid-1", {
          recent_matches: {
            matches: [{ id: "match-1" }],
            schema_version: 1,
            updated_at: timestamp("2026-04-28T08:00:00.000Z"),
          },
        }),
      ),
    );
  });
});

describe("Firestore private match subcollection rules", () => {
  it("rejects private match subcollection creates after the profile-v2 pivot", async () => {
    await seedProfile("uid-1");

    await assertFails(
      ownerDb().doc("profiles/uid-1/matches/match-1").set(
        {
          id: "match-1",
          source: "cloud_saved",
          trust: "client_uploaded",
        },
      ),
    );
  });

  it("rejects private match subcollection reads and deletes", async () => {
    await seedProfile("uid-1");
    await seedMatch("uid-1", "client-match", { trust: "client_uploaded" });

    await assertFails(ownerDb().doc("profiles/uid-1/matches/client-match").get());
    await assertFails(ownerDb().doc("profiles/uid-1/matches/client-match").delete());
  });
});
